group:
  - files:
      - source: .github/workflows/build-website.yml
        dest: .github/workflows/build-website.yml
      - source: .github/cc-by-license.md
        dest: LICENSE.md
      - source: _extensions/sdca-theme/
        dest: _extensions/steno-aarhus/sdca-theme/
      - source: directory.qmd
        dest: directory.qmd
      - source: .gitignore
        dest: .gitignore
    repos: |
      steno-aarhus/research
      steno-aarhus/epi-stats
      steno-aarhus/research-ops
      steno-aarhus/internationalization
      steno-aarhus/register-space
      steno-aarhus/epi
      steno-aarhus/coding-cafe
      steno-aarhus/cgm-ap
      steno-aarhus/living-project

