group:
  - files:
      - source: .github/workflows/build-website.yml
        dest: .github/workflows/build-website.yml
      - source: .github/cc-by-license.md
        dest: LICENSE.md
      - source: _extensions/sdca-theme/
        dest: _extensions/steno-aarhus/sdca-theme/
      - source: .gitignore
        dest: .gitignore
    repos: |
      steno-aarhus/research
      steno-aarhus/epi-stats
      steno-aarhus/research-ops
      steno-aarhus/internationalization
      steno-aarhus/register-space
      steno-aarhus/epi
      steno-aarhus/coding-cafe
      steno-aarhus/cgm-ap
      steno-aarhus/living-project
      steno-aarhus/evakom
      steno-aarhus/registers-project-database
      steno-aarhus/prodiap
      steno-aarhus/netvaerk-projektet
      steno-aarhus/steno-voice
  - files:
      # Don't want to overwrite the build-website.yml file in the steno-aarhus.github.io repo
      - source: .github/cc-by-license.md
        dest: LICENSE.md
      - source: _extensions/sdca-theme/
        dest: _extensions/steno-aarhus/sdca-theme/
      - source: .gitignore
        dest: .gitignore
    repos: |
      steno-aarhus/steno-aarhus.github.io
