project:
  type: sdca-theme

website:
  # TODO: Change title and URLs to fit the name of the repo
  title: "SDCA website template"
  site-url: "https://steno-aarhus.github.io/REPO-NAME/"
  repo-url: "https://github.com/steno-aarhus/REPO-NAME"
  
  # TODO: Remove announcement when website is ready
  announcement: 
    icon: info-circle
    content: "This website is a work in progress and might contain incomplete or placeholder content."
    type: light
  
  navbar:
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/REPO-NAME"

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor: 
  markdown:
    wrap: 72
    canonical: true
