name: Sync files across repos
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          owner: ${{ github.repository_owner }}
          app-id: ${{ vars.SYNC_FILES_APP_ID }}
          private-key: ${{ secrets.SYNC_FILES_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

        # Taken from https://github.com/actions/create-github-app-token/
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.app-token.outputs.token }}
          ASSIGNEES: lwjohnst86
          IS_FINE_GRAINED: true
          GIT_USERNAME: ${{ steps.app-token.outputs.app-slug }}[bot]
          GIT_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
          COMMIT_PREFIX: "chore(sync): :hammer: "
          COMMIT_EACH_FILE: false
          BRANCH_PREFIX: chore/seedcase-theme-sync
